// Shared currency/prose vs math contract. The browser suite runs every case
// through BOTH real Markdown engines, DOMPurify, and KaTeX (not just a regexp).
const literal = [
  'The mean is $4,814. Thus $20,000 is exceptionally high.',
  'Pay $5 and save $10.',
  'Pay $5, then $10, then $15.',
  'Between $2,000–$3,000 per month.',
  '$5-$10', '$5/$10', '$5 + $10 = $15',
  'USD $5.50, CAD $7.25, US$20, and A$30.',
  'A refund of -$5 and a cost of $0.50.',
  '$.99 or $1.99', '$1e3 versus $2e3', '$5k versus $10m',
  '$5 million versus $10 million',
  'It costs $ 5 and then $ 10.',
  'It costs $5.\nNext, $10.',
  'It costs $5.\n\nNext, $10.',
  'The symbol $ means dollars; the next $ is also literal.',
  '$hello world$', '$cost = high$', '$price + tax$', '$profit/loss$',
  '$x is y$', '$a cat$', '$5 per month$', '$5/month$',
  '$gross_income$', '$HOME$', '$PATH$', '${HOME}',
  'Use $HOME and $PATH.', 'Run $(pwd) and $(date).',
  '$? and $!', '$1 then $2',
  '$ x $', '$x $', '$ x$', '$x\ny$', '$x + 2',
  '$$$', '$$$$', 'foo$x$bar', 'US$x$',
  '$log files$', '$min wage$', '$max income$', '$sin tax$',
  '$2 + 2 = 4 per person$', '$x + y is total$',
  'log(x), x_t, 2 + 2 = 4, and beta are ordinary text without delimiters.',
  'Use data$income and data$tax.', 'Call $.ajax and $.get.',
  '$https://example.org/path$', '$name@example.org$',
  '$HOME/bin$PATH', '$5-$', '$5/$',
];

export const mathCases = [
  ...literal.map(source => ({ name: source, source, math: [], text: source, breaks: source.includes('\n') })),
  { name: 'screenshot bold amounts', source: 'Approximately **$3,383**, but one month reaches **$231,564**.', math: [], text: 'Approximately $3,383, but one month reaches $231,564.', bold: ['$3,383', '$231,564'] },
  { name: 'screenshot business income', source: 'The **$242,281** observation belongs to a self-employed person with a Type–Z flag. This person exceeds **$50,000 in 28 of 29 months**.', math: [], bold: ['$242,281', '$50,000 in 28 of 29 months'] },
  { name: 'escaped prices', source: String.raw`The mean is \$4,814. Thus \$20,000 is high.`, math: [], text: 'The mean is $4,814. Thus $20,000 is high.' },
  { name: 'escaped balanced dollars', source: String.raw`Literal \$x\$ and \$5\$.`, math: [], text: 'Literal $x$ and $5$.' },
  { name: 'escaped opener only', source: String.raw`Literal \$x$ here.`, math: [], text: 'Literal $x$ here.' },
  { name: 'code spans do not join', source: '`$HOME` and `$PATH` remain code.', math: [], code: ['$HOME', '$PATH'], text: '$HOME and $PATH remain code.' },
  { name: 'code equation stays code', source: '`$x + y$` and `\\(z\\)`', math: [], code: ['$x + y$', '\\(z\\)'] },
  { name: 'double-backtick code', source: '`` $x$ ` $y$ ``', math: [], code: ['$x$ ` $y$'] },
  { name: 'fenced code', source: '```sh\necho "$HOME $PATH"\necho "$x$"\n```', math: [], code: ['echo "$HOME $PATH"\necho "$x$"\n'] },
  { name: 'tilde fence', source: '~~~text\n$x$ and \\(y\\)\n~~~', math: [], code: ['$x$ and \\(y\\)\n'] },
  { name: 'indented code', source: '    $x$ and $y$', math: [], code: ['$x$ and $y$\n'] },
  { name: 'link destination', source: '[cost $5](https://example.org/$x$ "price $10")', math: [], text: 'cost $5' },
  { name: 'HTML entities are not delimiters', source: '&#36;x&#36; and &#36;5', math: [], text: '$x$ and $5' },
  ...[
    ['variable', '$x$', ['x']],
    ['numeric constant', '$5$', ['5']],
    ['numeric equation', '$2 + 2 = 4$', ['2 + 2 = 4']],
    ['subscripts', '$x_t$ and $p_e = 0.50$', ['x_t', 'p_e = 0.50']],
    ['Greek', '$β = 0.96$', ['β = 0.96']],
    ['powers', '$x^2 + y^2 = z^2$', ['x^2 + y^2 = z^2']],
    ['functions', '$log(x) + sin(y)$', ['log(x) + sin(y)']],
    ['fractions', String.raw`$\frac{a}{b} < 2$`, [String.raw`\frac{a}{b} < 2`]],
    ['custom macros', String.raw`$\ah(x)$ and $\E[x]$`, [String.raw`\ah(x)`, String.raw`\E[x]`]],
    ['explicit prose', String.raw`$x = \text{net income}$`, [String.raw`x = \text{net income}`]],
    ['nested text', String.raw`$\text{net \textbf{income}} = x$`, [String.raw`\text{net \textbf{income}} = x`]],
    ['roman label', String.raw`$x_{\mathrm{income}} = 2$`, [String.raw`x_{\mathrm{income}} = 2`]],
    ['currency inside explicit math', String.raw`\(\text{Cost: }\$5\)`, [String.raw`\text{Cost: }\$5`]],
    ['explicit arbitrary notation', String.raw`\(GDP = income\)`, ['GDP = income']],
    ['display', '$$x = 2$$', ['x = 2']],
    ['multiline display', '$$\nx = 2\n\ny = 3\n$$', ['x = 2\n\ny = 3']],
    ['bracket display', String.raw`\[x = \frac{1}{2}\]`, [String.raw`x = \frac{1}{2}`]],
    ['mixed prices and math', 'Pay $5 and $10; the model is $x + y = 2$.', ['x + y = 2']],
    ['math then prices', '$x_t$ costs $5, not $10.', ['x_t']],
    ['code then math', '`$HOME` and $x_t$', ['x_t']],
    ['escaped then math', String.raw`\$5 and $x_t$`, ['x_t']],
    ['math bold nesting', '**Estimate $x_t$ carefully**, not **$5** or **$10**.', ['x_t']],
    ['math in link label', '[Equation $x_t$](https://example.org/$y$)', ['x_t']],
    ['math table', '| Price | Model |\n|---|---|\n| $5 | $x_t$ |\n| $10 | $y_t$ |', ['x_t', 'y_t']],
    ['function word deliberately delimited', '$log$ and $min$', ['log', 'min']],
    ['product with explicit delimiters', String.raw`\(xy + GDP\)`, ['xy + GDP']],
    ['equations next to punctuation', '($x$), [$y$]; $z$!', ['x', 'y', 'z']],
    ['display in a list', '- Equation:\n\n  $$\n  x = 2\n  $$', ['x = 2']],
  ].map(([name, source, math]) => ({ name, source, math })),
];
